tasks:
  - name: Create Environment
    init: |
      python3 -m venv .venv
      source .venv/bin/activate
      export PIP_USER=false
      pip install -U pip
      pip install -U setuptools
      pip install -r requirements.txt
  - name: Create Environment
    command: |
      source .venv/bin/activate
      export PIP_USER=false
